version: '3.7'

services:
  proxy:
    image: caddy:2-alpine
    restart: unless-stopped
    links:
    - akkoma
    ports:
    - 443:443
    - 80:80
    volumes:
      - ./docker-resources/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy-data:/data
      - ./caddy-config:/config
